# Generated by Django 3.0.6 on 2020-05-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200516_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofil',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
